module.exports = {
  '@typescript-eslint/ban-ts-comment': 'off',
  '@typescript-eslint/ban-types': 'off',
  '@typescript-eslint/consistent-type-assertions': 'warn',
  '@typescript-eslint/consistent-type-imports': 'warn',
  '@typescript-eslint/method-signature-style': ['error', 'property'],
  '@typescript-eslint/no-empty-function': 'off',
  '@typescript-eslint/no-empty-interface': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
  '@typescript-eslint/no-inferrable-types': 'off',
  '@typescript-eslint/no-namespace': 'off',
  '@typescript-eslint/no-non-null-assertion': 'off',
  '@typescript-eslint/no-unused-expressions': ['error', {allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true}],
  '@typescript-eslint/no-unused-vars': ['warn', {args: 'none', ignoreRestSiblings: true}],
  '@typescript-eslint/no-use-before-define': ['error', {classes: false, functions: false, typedefs: false, variables: false}],
  '@typescript-eslint/no-var-requires': 'off',
  '@typescript-eslint/return-await': 'error',
  'no-dupe-class-members': 'off',
  'no-undef': 'off',
  'no-use-before-define': 'off',
  'no-var': 'off',
  'prefer-rest-params': 'off',
};
